//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentificadorAnimal
    {
        public int idIdentificadorAnimal { get; set; }
        public string codigoIdentificador { get; set; }
        public Nullable<int> Ani_idAnimal { get; set; }
        public Nullable<byte> TpI_idTipoIdentificador { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual TipoIdentificador TipoIdentificador { get; set; }
    }
}
